In [145]:
import requests

response = requests.get("https://services6.arcgis.com/bdPqSfflsdgFRVVM/arcgis/rest/services/crime_data_1_auto_update/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json")

In [146]:
import csv 
import pandas as pd
import numpy as np

In [147]:
Crime2023Part1 = pd.read_csv('./datasets/Crime2023Part1.csv')
Crime2023Part2 = pd.read_csv('./datasets/Crime2023Part2.csv')
Crime2024Part2 = pd.read_csv('./datasets/Crime2024Part2.csv')
Crime2024Part1 = pd.read_csv('./datasets/Crime2024Part1.csv')
Crime2018Part1 = pd.read_csv('./datasets/Crime2018Part1.csv')

In [148]:

Crime2024Part1.dropna(inplace=True)
Crime2023Part2.dropna(inplace=True)
Crime2023Part1.dropna(inplace=True)
Crime2024Part2.dropna(inplace=True)
Crime2018Part1.dropna(inplace=True)

In [149]:
Crime2023Part1
Crime2023Part2
Crime2024Part2

,X,Y,DATEEND,TIMESTART,TIMEEND,ADDRESS,QualityOfLife,CODE_DEFINED,LAT,LONG,ObjectId
0,-8.479661e+06,5.317442e+06,2024/01/20 05:00:00+00,355,355,1200 S GEDDES ST,True,CRIMINAL MISCHIEF,43.035925,-76.174089,1
1,-8.472376e+06,5.321695e+06,2024/01/20 05:00:00+00,941,1000,300 HILLSDALE AVE,False,CRIMINAL MISCHIEF,43.063848,-76.108649,2
2,-8.477444e+06,5.319086e+06,2024/01/21 05:00:00+00,11,11,500 S CLINTON ST,False,OFFN AGAINST FAMILY,43.046721,-76.154175,3
3,-8.480678e+06,5.319991e+06,2024/01/13 05:00:00+00,941,941,1800 E FAYETTE ST,False,SIMPLE ASSAULT,43.052661,-76.183227,4
4,-8.476041e+06,5.321574e+06,2024/01/20 05:00:00+00,1056,1056,600 PARK ST,False,OFFN AGAINST FAMILY,43.063055,-76.141569,5
...,...,...,...,...,...,...,...,...,...,...,...
856,-8.476023e+06,5.321743e+06,2024/01/13 05:00:00+00,1,15,900 HIGHLAND ST,False,SIMPLE ASSAULT,43.064163,-76.141408,857
857,-8.476075e+06,5.318279e+06,2024/01/13 05:00:00+00,313,313,100 LIGHT CT,False,OFFN AGAINST FAMILY,43.041420,-76.141881,858
858,-8.476856e+06,5.316991e+06,2024/01/12 05:00:00+00,2318,2318,1400 S SALINA ST,False,POSSESSION/USE DRUG,43.032968,-76.148895,859
859,-8.476908e+06,5.321811e+06,2024/01/13 05:00:00+00,136,136,100 NEUTRAL CT,False,CRIMINAL MISCHIEF,43.064610,-76.149365,860
860,-8.477362e+06,5.321635e+06,2024/01/13 05:00:00+00,854,854,2000 LODI ST,False,OFFN AGAINST FAMILY,43.063450,-76.153437,861

In [150]:
print(Crime2023Part1.columns)
print(Crime2023Part2.columns)
print(Crime2024Part2.columns)
print(Crime2024Part1.columns)

Index(['X', 'Y', 'DATEEND', 'TIMESTART', 'TIMEEND', 'ADDRESS', 'Arrest',
       'LarcenyCode', 'CODE_DEFINED', 'LAT', 'LONG', 'ObjectId'],
      dtype='object')
Index(['X', 'Y', 'DATEEND', 'TIMESTART', 'TIMEEND', 'ADDRESS', 'QualityOfLife',
       'CODE_DEFINED', 'LAT', 'LONG', 'ObjectId'],
      dtype='object')
Index(['X', 'Y', 'DATEEND', 'TIMESTART', 'TIMEEND', 'ADDRESS', 'QualityOfLife',
       'CODE_DEFINED', 'LAT', 'LONG', 'ObjectId'],
      dtype='object')
Index(['X', 'Y', 'DATEEND', 'TIMESTART', 'TIMEEND', 'ADDRESS', 'Arrest',
       'LarcenyCode', 'CODE_DEFINED', 'LAT', 'LONG', 'ObjectId'],
      dtype='object')

In [151]:
Crime2023Part1.ADDRESS.unique

<bound method Series.unique of 4                         1 DESTINY USA DR
5                         1 DESTINY USA DR
13                        1 DESTINY USA DR
14      0 S WARREN ST & E WATER ST
18                        1 DESTINY USA DR
                       ...
6581                      800 BURNET AV
6584                      800 BEAR ST
6607                  800 E BRIGHTON AV
6612                  800 E WILLOW ST
6616                      800 ERIE BLVD W
Name: ADDRESS, Length: 752, dtype: object>

In [152]:
Crime2023Part1[Crime2023Part1['CODE_DEFINED'] == 'LARCENY']

,X,Y,DATEEND,TIMESTART,TIMEEND,ADDRESS,Arrest,LarcenyCode,CODE_DEFINED,LAT,LONG,ObjectId
4,-8.479620e+06,5.322322e+06,2023/08/24 00:00:00+00,1341,1341,1 DESTINY USA DR,Yes,Shoplifting,LARCENY,43.067961,-76.173723,5
5,-8.479620e+06,5.322322e+06,2023/08/24 00:00:00+00,1730,1730,1 DESTINY USA DR,Yes,Shoplifting,LARCENY,43.067961,-76.173723,6
13,-8.479620e+06,5.322322e+06,2023/11/29 00:00:00+00,1530,1536,1 DESTINY USA DR,Yes,Shoplifting,LARCENY,43.067961,-76.173723,14
18,-8.479620e+06,5.322322e+06,2023/07/25 00:00:00+00,1959,2030,1 DESTINY USA DR,Yes,Shoplifting,LARCENY,43.067961,-76.173723,19
22,-8.477073e+06,5.318898e+06,2023/06/10 00:00:00+00,2100,2300,0 S WARREN ST & MADISON ST,Yes,From Motor Vehicle,LARCENY,43.045488,-76.150840,23
...,...,...,...,...,...,...,...,...,...,...,...,...
6507,-8.476631e+06,5.321087e+06,2023/10/03 00:00:00+00,1513,1513,600 BUTTERNUT ST,Yes,Shoplifting,LARCENY,43.059859,-76.146872,6508
6508,-8.477529e+06,5.321606e+06,2023/10/28 00:00:00+00,1130,1135,900 N SALINA ST,Yes,From Building,LARCENY,43.063263,-76.154935,6509
6528,-8.478278e+06,5.323327e+06,2023/09/02 00:00:00+00,1205,1206,600 WOLF ST,Yes,From Motor Vehicle,LARCENY,43.074553,-76.161664,6529
6535,-8.477704e+06,5.320980e+06,2023/08/25 00:00:00+00,1335,1335,700 N CLINTON ST,Yes,From Mailbox,LARCENY,43.059155,-76.156508,6536
6581,-8.474752e+06,5.319894e+06,2023/09/04 00:00:00+00,0630,946,800 BURNET AV,Yes,From Motor Vehicle,LARCENY,43.052025,-76.129996,6582

In [154]:
allCrimeData = pd.concat([Crime2023Part1, Crime2023Part2, Crime2024Part1, Crime2024Part2], ignore_index=True)
allCrimeData.drop(columns=['X', 'Y', 'QualityOfLife', 'ObjectId', 'Arrest', 'LarcenyCode' ], inplace=True)

In [155]:
allCrimeData

,DATEEND,TIMESTART,TIMEEND,ADDRESS,CODE_DEFINED,LAT,LONG
0,2023/08/24 00:00:00+00,1341,1341,1 DESTINY USA DR,LARCENY,43.067961,-76.173723
1,2023/08/24 00:00:00+00,1730,1730,1 DESTINY USA DR,LARCENY,43.067961,-76.173723
2,2023/11/29 00:00:00+00,1530,1536,1 DESTINY USA DR,LARCENY,43.067961,-76.173723
3,2023/03/26 00:00:00+00,0525,530,0 S WARREN ST & E WATER ST,MV THEFT,43.050519,-76.150768
4,2023/07/25 00:00:00+00,1959,2030,1 DESTINY USA DR,LARCENY,43.067961,-76.173723
...,...,...,...,...,...,...,...
8341,2024/01/13 05:00:00+00,1,15,900 HIGHLAND ST,SIMPLE ASSAULT,43.064163,-76.141408
8342,2024/01/13 05:00:00+00,313,313,100 LIGHT CT,OFFN AGAINST FAMILY,43.041420,-76.141881
8343,2024/01/12 05:00:00+00,2318,2318,1400 S SALINA ST,POSSESSION/USE DRUG,43.032968,-76.148895
8344,2024/01/13 05:00:00+00,136,136,100 NEUTRAL CT,CRIMINAL MISCHIEF,43.064610,-76.149365
8345,2024/01/13 05:00:00+00,854,854,2000 LODI ST,OFFN AGAINST FAMILY,43.063450,-76.153437

In [156]:
allCrimeData.isna().sum()

DATEEND         0
TIMESTART       0
TIMEEND         0
ADDRESS         0
CODE_DEFINED    0
LAT             0
LONG            0
dtype: int64

In [157]:
crimeWeights ={
    "LARCENY": 1,
    "BURGLARY": 2,
    "MOTOR VEHICLE THEFT": 3,
    "ROBBERY": 4,
    "AGGRAVATED ASSAULT": 5,
}

# Group the data by address and calculate the sum of crime weights
address_crime_weights = allCrimeData.groupby('ADDRESS')['CODE_DEFINED'].apply(lambda x: x.map(crimeWeights).sum())

# Assign the crime weights to the addresses
allCrimeData['CRIME_WEIGHT'] = allCrimeData['ADDRESS'].map(address_crime_weights)

allCrimeData

,DATEEND,TIMESTART,TIMEEND,ADDRESS,CODE_DEFINED,LAT,LONG,CRIME_WEIGHT
0,2023/08/24 00:00:00+00,1341,1341,1 DESTINY USA DR,LARCENY,43.067961,-76.173723,242.0
1,2023/08/24 00:00:00+00,1730,1730,1 DESTINY USA DR,LARCENY,43.067961,-76.173723,242.0
2,2023/11/29 00:00:00+00,1530,1536,1 DESTINY USA DR,LARCENY,43.067961,-76.173723,242.0
3,2023/03/26 00:00:00+00,0525,530,0 S WARREN ST & E WATER ST,MV THEFT,43.050519,-76.150768,0.0
4,2023/07/25 00:00:00+00,1959,2030,1 DESTINY USA DR,LARCENY,43.067961,-76.173723,242.0
...,...,...,...,...,...,...,...,...
8341,2024/01/13 05:00:00+00,1,15,900 HIGHLAND ST,SIMPLE ASSAULT,43.064163,-76.141408,1.0
8342,2024/01/13 05:00:00+00,313,313,100 LIGHT CT,OFFN AGAINST FAMILY,43.041420,-76.141881,1.0
8343,2024/01/12 05:00:00+00,2318,2318,1400 S SALINA ST,POSSESSION/USE DRUG,43.032968,-76.148895,1.0
8344,2024/01/13 05:00:00+00,136,136,100 NEUTRAL CT,CRIMINAL MISCHIEF,43.064610,-76.149365,0.0
8345,2024/01/13 05:00:00+00,854,854,2000 LODI ST,OFFN AGAINST FAMILY,43.063450,-76.153437,0.0

In [161]:

import folium

# Create a map object
m = folium.Map(location=['43.067961', '-76.173723'], zoom_start=12)

for index, row in allCrimeData.iterrows():
    folium.Marker(
        location=[row['LAT'], row['LONG']],
        popup=row['CODE_DEFINED'],
        icon=folium.Icon(color='red')
    ).add_to(m)


m.save('crime_map.html')